version: "3.3"

networks:
  backend:
    external: true

services:
  auth-service:
    container_name: auth-service
    networks:
      - backend
    build: .
    restart: always
    env_file: /srv/production.env