version: "3.3"

networks:
  backend:
    external: true

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 80:80
    networks:
      - backend
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./pages:/var/www/nginx