variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  only:
    refs:
      - master
  tags:
    - deploy-prod
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml run admin-gateway yarn test
    - docker-compose -f docker-compose.prod.yml up -d
