version: "3.3"

networks:
  backend:
    external: true

services:
  admin-gateway:
    container_name: admin-gateway
    ports:
      - "8080:8080"
    networks:
      - backend
    build: .
    restart: always
    env_file: development.env