version: "3.3"

networks:
  backend:
    external: true

services:
  support-service:
    container_name: support-service
    networks:
      - backend
    build: .
    restart: always
    env_file: /srv/production.env